ChecklistItem.delete_all

ChecklistItem.create(category: 'determine', category_name: 'Determine If You Need a Business License', order_number: 1, item_text: "Determine if you need a business license")

ChecklistItem.create(category: 'planning', category_name: 'Plan Out Your Business', order_number: 1, item_text: "Write a business plan")
ChecklistItem.create(category: 'planning', category_name: 'Plan Out Your Business', order_number: 2, item_text: "Check out the classes at SBDC")
ChecklistItem.create(category: 'planning', category_name: 'Plan Out Your Business', order_number: 3, item_text: "Get feedback on your business plan")
ChecklistItem.create(category: 'planning', category_name: 'Plan Out Your Business', order_number: 4, item_text: "Connect with a mentor")
ChecklistItem.create(category: 'planning', category_name: 'Plan Out Your Business', order_number: 5, item_text: "Determine if entrepreneurship is right for you right now")

ChecklistItem.create(category: 'finance', category_name: 'Create a Financial Plan', order_number: 1, item_text: "Create a financial plan")
ChecklistItem.create(category: 'finance', category_name: 'Create a Financial Plan', order_number: 2, item_text: "Calculate needed starting capital")
ChecklistItem.create(category: 'finance', category_name: 'Create a Financial Plan', order_number: 3, item_text: "Calculate financial projections")
ChecklistItem.create(category: 'finance', category_name: 'Create a Financial Plan', order_number: 4, item_text: "Calculate your break even point")
ChecklistItem.create(category: 'finance', category_name: 'Create a Financial Plan', order_number: 5, item_text: "Review plan with FREE resources like SBDC")
ChecklistItem.create(category: 'finance', category_name: 'Create a Financial Plan', order_number: 6, item_text: "Explore available loans from the city, the bank, and friends and family")

ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 1, item_text: "Consider home-based vs. brick and mortar")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 2, item_text: "Consider the size of the property you need for your business")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 3, item_text: "Identify several locations well-suited for your business")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 4, item_text: "Get to know the BID services")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 5, item_text: "Consider working with a commercial broker to help with this process")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 6, item_text: "Explore a FREE location selection tool from Gateway Cities Council of Governments ")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 7, item_text: "See if your business type is allowed in the locations you've selected")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 8, item_text: "Draft a Letter of Intent (LOI)")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 9, item_text: "Get feedback on your lease by a lawyer or commercial broker")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 10, item_text: "Create a site plan")
ChecklistItem.create(category: 'location', category_name: 'Find a Location', order_number: 11, item_text: "Draft and sign the lease")

ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 1, item_text: "Determine your business structure")
ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 2, item_text: "Create a business name and consider the branding implications")
ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 3, item_text: "Register your Fictitious Business Name (FBN) with LA county")
ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 4, item_text: "Apply for a Federal Employer Identification Number ")
ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 5, item_text: "Apply for a California State Board of Equalization Seller's Permit [Retail Only]")
ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 6, item_text: "Determine which licenses and permits are required for your business type")
ChecklistItem.create(category: 'register', category_name: 'Register Your Business', order_number: 7, item_text: "Apply for a City of Long Beach Business License")

ChecklistItem.create(category: 'license', category_name: 'Apply for a Business License', order_number: 1, item_text: "Understand the differences in terminology")
ChecklistItem.create(category: 'license', category_name: 'Apply for a Business License', order_number: 2, item_text: "Determine what type(s) of business licenses you need")
ChecklistItem.create(category: 'license', category_name: 'Apply for a Business License', order_number: 3, item_text: "Determine if you need an annual or short-term license")
ChecklistItem.create(category: 'license', category_name: 'Apply for a Business License', order_number: 4, item_text: "Fill out the Business License Application")
ChecklistItem.create(category: 'license', category_name: 'Apply for a Business License', order_number: 5, item_text: "Determine if you need to pay Business Improvement District (BID) fees")
ChecklistItem.create(category: 'license', category_name: 'Apply for a Business License', order_number: 6, item_text: "Determine if you need additional licenses")

ChecklistItem.create(category: 'permits', category_name: 'Permits', order_number: 1, item_text: "Bring plans to the 4th Floor of City Hall for plan check")
ChecklistItem.create(category: 'permits', category_name: 'Permits', order_number: 2, item_text: "Pick up your plans")
ChecklistItem.create(category: 'permits', category_name: 'Permits', order_number: 3, item_text: "Pay permit fees")
ChecklistItem.create(category: 'permits', category_name: 'Permits', order_number: 4, item_text: "Check the status of your permits")

ChecklistItem.create(category: 'inspections', category_name: 'Inspections', order_number: 1, item_text: "Schedule inspections")
ChecklistItem.create(category: 'inspections', category_name: 'Inspections', order_number: 2, item_text: "Confirm inspection")
ChecklistItem.create(category: 'inspections', category_name: 'Inspections', order_number: 3, item_text: "Meet the inspector")
ChecklistItem.create(category: 'inspections', category_name: 'Inspections', order_number: 4, item_text: "Receive Certificate of Occupancy (CO)")

ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 1, item_text: "Receive Certificate of Occupancy")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 2, item_text: "Receive Business License")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 3, item_text: "Hire employees")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 4, item_text: "Put up workplace posters")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 5, item_text: "Pay your business taxes")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 6, item_text: "Consider joining the Chamber of Commerce")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 7, item_text: "Make any necessary edits to your Business License")
ChecklistItem.create(category: 'grow', category_name: 'Open Your Business', order_number: 8, item_text: "Start doing business!")

ChecklistItem.create(category: 'city_contracts', category_name: 'Do Business with the City', order_number: 1, item_text: "Register your business services on PlanetBids")
